# Generated by Django 4.0.6 on 2022-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=255)),
                ('EventDesc', models.CharField(max_length=500)),
            ],
        ),
    ]
